security:
  basic:
    enabled: false
    
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc\:mysql\:\/\/localhost\/springboot?characterEncoding=utf8&useUnicode=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=UTC
    username: root
    password: mysqldb861110
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    

logging:
  level:
    org:
      springframework:
        secutiry: INFO

    